# SQL-Based Data Analysis Using Subqueries, CTEs, and Window Functions

## Celebal Technologies Internship 2026

### Week 3 Assignment

# Importing Required Libraries

In [1]:
import pandas as pd
import sqlite3

# Loading the Superstore Dataset

In [3]:
df = pd.read_csv(
    "data/Sample - Superstore.csv",
    encoding="latin1"
)

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

# Exploring the Dataset

In [4]:
df.shape

(9994, 21)

In [5]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

In [7]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

# Creating SQLite Database

In [8]:
conn = sqlite3.connect("superstore.db")

print("Database Connected Successfully")

Database Connected Successfully

# Creating Superstore Raw Table

In [9]:
df.to_sql(
    "superstore_raw",
    conn,
    if_exists="replace",
    index=False
)

print("Table Created Successfully")

Table Created Successfully

# Verifying the Table

In [10]:
pd.read_sql_query(
    "SELECT * FROM superstore_raw LIMIT 5;",
    conn
)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

# Displaying Table Schema

In [11]:
pd.read_sql_query(
    "PRAGMA table_info(superstore_raw);",
    conn
)

    cid           name     type  notnull dflt_value  pk
0     0         Row ID  INTEGER        0       None   0
1     1       Order ID     TEXT        0       None   0
2     2     Order Date     TEXT        0       None   0
3     3      Ship Date     TEXT        0       None   0
4     4      Ship Mode     TEXT        0       None   0
5     5    Customer ID     TEXT        0       None   0
6     6  Customer Name     TEXT        0       None   0
7     7        Segment     TEXT        0       None   0
8     8        Country     TEXT        0       None   0
9     9           City     TEXT        0       None   0
10   10          State     TEXT        0       None   0
11   11    Postal Code  INTEGER        0       None   0
12   12         Region     TEXT        0       None   0
13   13     Product ID     TEXT        0       None   0
14   14       Category     TEXT        0       None   0
15   15   Sub-Category     TEXT        0       None   0
16   16   Product Name     TEXT        0       None   0
17   17          Sales     REAL        0       None   0
18   18       Quantity  INTEGER        0       None   0
19   19       Discount     REAL        0       None   0
20   20         Profit     REAL        0       None   0

# Creating Customer Table

In [12]:
conn.execute("""
CREATE TABLE customers AS

SELECT DISTINCT

    "Customer ID",
    "Customer Name",
    Segment

FROM superstore_raw;
""")

print("Customers Table Created")

Customers Table Created

# Creating Orders Table

In [13]:
conn.execute("""
CREATE TABLE orders AS

SELECT DISTINCT

    "Order ID",
    "Order Date",
    "Ship Date",
    "Ship Mode",
    "Customer ID",
    Sales,
    Quantity,
    Discount,
    Profit

FROM superstore_raw;
""")

print("Orders Table Created")

Orders Table Created

# Creating Products Table

In [14]:
conn.execute("""
CREATE TABLE products AS

SELECT DISTINCT

    "Product ID",
    "Product Name",
    Category,
    "Sub-Category"

FROM superstore_raw;
""")

print("Products Table Created")

Products Table Created

# Verifying Created Tables

In [15]:
pd.read_sql_query("""
SELECT name

FROM sqlite_master

WHERE type='table';
""", conn)

             name
0  superstore_raw
1       customers
2          orders
3        products

# Creating Helper Function

In [17]:
def run_query(query):
    return pd.read_sql_query(query, conn)

# Applying Subqueries

## Q1 Orders With Sales Greater Than Average Sales

In [18]:
run_query("""
SELECT *

FROM superstore_raw

WHERE Sales >
(
SELECT AVG(Sales)

FROM superstore_raw
);
""")

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
3,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
4,11,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2355,9974,US-2016-103674,12/6/2016,12/10/2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,TEC-PH-10004080,Technology,Phones,Avaya 5410 Digital phone,271.9600,5,0.20,27.1960
2356,9977,US-2016-103674,12/6/2016,12/10/2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,TEC-PH-10002496,Technology,Phones,Cisco SPA301,249.5840,2,0.20,31.1980
2357,9980,US-2016-103674,12/6/2016,12/10/2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,OFF-BI-10002026,Office Supplies,Binders,Ibico Recycled Linen-Style Covers,437.4720,14,0.20,153.1152
2358,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
2359,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

## Q2 Highest Order Of Each Customer

In [19]:
run_query("""
SELECT *

FROM superstore_raw s

WHERE Sales =
(
SELECT MAX(Sales)

FROM superstore_raw

WHERE "Customer ID" = s."Customer ID"
);
""")

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
1,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
2,11,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
3,25,CA-2015-106320,9/25/2015,9/30/2015,Standard Class,EB-13870,Emily Burns,Consumer,United States,Orem,...,84057,West,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.6300,3,0.00,240.2649
4,28,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,7,0.50,-1665.0522
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
790,9926,CA-2015-159534,3/20/2015,3/23/2015,First Class,DH-13075,Dave Hallsten,Corporate,United States,New York City,...,10035,East,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,1087.9360,8,0.20,353.5792
791,9930,CA-2016-129630,9/4/2016,9/4/2016,Same Day,IM-15055,Ionia McGrath,Consumer,United States,San Francisco,...,94122,West,TEC-CO-10003763,Technology,Copiers,Canon PC1060 Personal Laser Copier,2799.9600,5,0.20,944.9865
792,9949,CA-2017-121559,6/1/2017,6/3/2017,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,46203,Central,OFF-AP-10002945,Office Supplies,Appliances,Honeywell Enviracaire Portable HEPA Air Cleane...,2405.2000,8,0.00,793.7160
793,9969,CA-2017-153871,12/11/2017,12/17/2017,Standard Class,RB-19435,Richard Bierner,Consumer,United States,Plainfield,...,7060,East,OFF-BI-10004600,Office Supplies,Binders,Ibico Ibimaster 300 Manual Binding System,735.9800,2,0.00,331.1910
794,9980,US-2016-103674,12/6/2016,12/10/2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,OFF-BI-10002026,Office Supplies,Binders,Ibico Recycled Linen-Style Covers,437.4720,14,0.20,153.1152

# Common Table Expressions (CTEs)

## Q3 Total Sales Per Customer Using CTE

In [20]:
run_query("""
WITH CustomerSales AS
(
SELECT

"Customer ID",

"Customer Name",

SUM(Sales) AS Total_Sales

FROM superstore_raw

GROUP BY

"Customer ID",

"Customer Name"
)

SELECT *

FROM CustomerSales

ORDER BY Total_Sales DESC;
""")

    Customer ID    Customer Name  Total_Sales
0      SM-20320      Sean Miller    25043.050
1      TC-20980     Tamara Chand    19052.218
2      RB-19360     Raymond Buch    15117.339
3      TA-21385     Tom Ashbrook    14595.620
4      AB-10105    Adrian Barton    14473.571
..          ...              ...          ...
788    RS-19870       Roy Skaria       22.328
789    MG-18205  Mitch Gastineau       16.739
790    CJ-11875     Carl Jackson       16.520
791    LD-16855     Lela Donovan        5.304
792    TS-21085    Thais Sissman        4.833

[793 rows x 3 columns]

## Q4 Customers Above Average Total Sales

In [21]:
run_query("""
WITH CustomerSales AS
(
SELECT

"Customer ID",

"Customer Name",

SUM(Sales) AS Total_Sales

FROM superstore_raw

GROUP BY

"Customer ID",

"Customer Name"
)

SELECT *

FROM CustomerSales

WHERE Total_Sales >
(
SELECT AVG(Total_Sales)

FROM CustomerSales
);
""")

    Customer ID     Customer Name  Total_Sales
0      AA-10315        Alex Avila     5563.560
1      AA-10645     Anna Andreadi     5086.935
2      AB-10060   Adam Bellavance     7755.620
3      AB-10105     Adrian Barton    14473.571
4      AC-10450           Amy Cox     5527.846
..          ...               ...          ...
289    VW-21775   Victoria Wilson     6134.038
290    WB-21850     William Brown     6160.102
291    YC-21895    Yoseph Carroll     5454.350
292    YS-21880     Yana Sorensen     6720.444
293    ZC-21910  Zuschuss Carroll     8025.707

[294 rows x 3 columns]

# Window Functions

## Q5 Assign Row Number Based On Sales

In [22]:
run_query("""
SELECT

"Customer Name",

Sales,

ROW_NUMBER()

OVER
(
ORDER BY Sales DESC
)

AS Row_Number

FROM superstore_raw;
""")

         Customer Name      Sales  Row_Number
0          Sean Miller  22638.480           1
1         Tamara Chand  17499.950           2
2         Raymond Buch  13999.960           3
3         Tom Ashbrook  11199.968           4
4         Hunter Lopez  10499.970           5
...                ...        ...         ...
9989     Henry Goldwyn      0.876        9990
9990     Jas O'Carroll      0.852        9991
9991       Ken Brennan      0.836        9992
9992    Roland Schwarz      0.556        9993
9993  Zuschuss Carroll      0.444        9994

[9994 rows x 3 columns]

## Q6 Ranking Customers Based On Sales

In [23]:
run_query("""
SELECT

"Customer Name",

Sales,

RANK()

OVER
(
ORDER BY Sales DESC
)

AS Sales_Rank

FROM superstore_raw;
""")

         Customer Name      Sales  Sales_Rank
0          Sean Miller  22638.480           1
1         Tamara Chand  17499.950           2
2         Raymond Buch  13999.960           3
3         Tom Ashbrook  11199.968           4
4         Hunter Lopez  10499.970           5
...                ...        ...         ...
9989     Henry Goldwyn      0.876        9990
9990     Jas O'Carroll      0.852        9991
9991       Ken Brennan      0.836        9992
9992    Roland Schwarz      0.556        9993
9993  Zuschuss Carroll      0.444        9994

[9994 rows x 3 columns]

# Business Queries

## Q7 Top 10 Customers Based on Total Sales

In [24]:
run_query("""
WITH CustomerSales AS
(
SELECT

"Customer ID",

"Customer Name",

SUM(Sales) AS Total_Sales

FROM superstore_raw

GROUP BY

"Customer ID",

"Customer Name"
)

SELECT *

FROM CustomerSales

ORDER BY Total_Sales DESC

LIMIT 10;
""")

  Customer ID       Customer Name  Total_Sales
0    SM-20320         Sean Miller    25043.050
1    TC-20980        Tamara Chand    19052.218
2    RB-19360        Raymond Buch    15117.339
3    TA-21385        Tom Ashbrook    14595.620
4    AB-10105       Adrian Barton    14473.571
5    KL-16645        Ken Lonsdale    14175.229
6    SC-20095        Sanjit Chand    14142.334
7    HL-15040        Hunter Lopez    12873.298
8    SE-20110        Sanjit Engle    12209.438
9    CC-12370  Christopher Conant    12129.072

## Q8 Bottom 10 Customers Based on Total Sales

In [25]:
run_query("""
WITH CustomerSales AS
(
SELECT

"Customer ID",

"Customer Name",

SUM(Sales) AS Total_Sales

FROM superstore_raw

GROUP BY

"Customer ID",

"Customer Name"
)

SELECT *

FROM CustomerSales

ORDER BY Total_Sales

LIMIT 10;
""")

  Customer ID    Customer Name  Total_Sales
0    TS-21085    Thais Sissman        4.833
1    LD-16855     Lela Donovan        5.304
2    CJ-11875     Carl Jackson       16.520
3    MG-18205  Mitch Gastineau       16.739
4    RS-19870       Roy Skaria       22.328
5    SG-20890   Susan Gilcrest       47.946
6    RE-19405  Ricardo Emerson       48.360
7    LB-16735     Larry Blacks       50.188
8    AS-10135     Adrian Shami       58.820
9    JC-15340  Jasper Cacioppo       71.263

## Q9 Customers Who Placed Only One Order

In [26]:
run_query("""
WITH CustomerSales AS
(
SELECT

"Customer ID",

"Customer Name",

SUM(Sales) AS Total_Sales

FROM superstore_raw

GROUP BY

"Customer ID",

"Customer Name"
)

SELECT *

FROM CustomerSales

ORDER BY Total_Sales

LIMIT 10;
""")

  Customer ID    Customer Name  Total_Sales
0    TS-21085    Thais Sissman        4.833
1    LD-16855     Lela Donovan        5.304
2    CJ-11875     Carl Jackson       16.520
3    MG-18205  Mitch Gastineau       16.739
4    RS-19870       Roy Skaria       22.328
5    SG-20890   Susan Gilcrest       47.946
6    RE-19405  Ricardo Emerson       48.360
7    LB-16735     Larry Blacks       50.188
8    AS-10135     Adrian Shami       58.820
9    JC-15340  Jasper Cacioppo       71.263

## Q10 Ranking Customers Based on Total Sales

In [27]:
run_query("""
WITH CustomerSales AS
(
SELECT

"Customer ID",

"Customer Name",

SUM(Sales) AS Total_Sales

FROM superstore_raw

GROUP BY

"Customer ID",

"Customer Name"
)

SELECT

*,

RANK()

OVER
(
ORDER BY Total_Sales DESC
)

AS Customer_Rank

FROM CustomerSales;
""")

    Customer ID    Customer Name  Total_Sales  Customer_Rank
0      SM-20320      Sean Miller    25043.050              1
1      TC-20980     Tamara Chand    19052.218              2
2      RB-19360     Raymond Buch    15117.339              3
3      TA-21385     Tom Ashbrook    14595.620              4
4      AB-10105    Adrian Barton    14473.571              5
..          ...              ...          ...            ...
788    RS-19870       Roy Skaria       22.328            789
789    MG-18205  Mitch Gastineau       16.739            790
790    CJ-11875     Carl Jackson       16.520            791
791    LD-16855     Lela Donovan        5.304            792
792    TS-21085    Thais Sissman        4.833            793

[793 rows x 4 columns]

## Q11 Customer Sales Ranking Using JOIN, CTE and Window Function

In [28]:
run_query("""
WITH CustomerSales AS
(
SELECT

"Customer ID",

SUM(Sales) AS Total_Sales

FROM superstore_raw

GROUP BY "Customer ID"
)

SELECT

c."Customer ID",

c."Customer Name",

cs.Total_Sales,

RANK()

OVER
(
ORDER BY cs.Total_Sales DESC
)

AS Customer_Rank

FROM customers c

JOIN CustomerSales cs

ON c."Customer ID" = cs."Customer ID"

ORDER BY Customer_Rank;
""")

    Customer ID    Customer Name  Total_Sales  Customer_Rank
0      SM-20320      Sean Miller    25043.050              1
1      TC-20980     Tamara Chand    19052.218              2
2      RB-19360     Raymond Buch    15117.339              3
3      TA-21385     Tom Ashbrook    14595.620              4
4      AB-10105    Adrian Barton    14473.571              5
..          ...              ...          ...            ...
788    RS-19870       Roy Skaria       22.328            789
789    MG-18205  Mitch Gastineau       16.739            790
790    CJ-11875     Carl Jackson       16.520            791
791    LD-16855     Lela Donovan        5.304            792
792    TS-21085    Thais Sissman        4.833            793

[793 rows x 4 columns]

# Business Insights

- Customers with sales above the average contribute significantly to revenue.
- The ranking identifies the highest-performing customers.
- Window functions simplify ranking without complex subqueries.
- CTEs improve query readability and maintainability.
- Combining JOIN, CTE, and Window Functions provides meaningful business insights for decision-making.