# E-Commerce Sales Database Analysis

## Celebal Summer Internship 2026

Week 2 Assignment

# Importing Required Libraries

In [1]:
import sqlite3
import pandas as pd

# Creating Database Connection

In [2]:
conn = sqlite3.connect("ecommerce.db")

cursor = conn.cursor()

print("Database Connected Successfully")

Database Connected Successfully

# Creating Database Tables

In [3]:
cursor.execute("""
CREATE TABLE customers (
    customer_id INTEGER PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    city TEXT NOT NULL,
    state TEXT NOT NULL,
    join_date DATE NOT NULL,
    is_premium BOOLEAN DEFAULT FALSE
)
""")

In [4]:
cursor.execute("""
CREATE TABLE products (
    product_id INTEGER PRIMARY KEY,
    product_name TEXT NOT NULL,
    category TEXT NOT NULL,
    brand TEXT NOT NULL,
    unit_price REAL NOT NULL,
    stock_qty INTEGER NOT NULL
)
""")

In [5]:
cursor.execute("""
CREATE TABLE orders (
    order_id INTEGER PRIMARY KEY,
    customer_id INTEGER,
    order_date DATE,
    status TEXT,
    total_amount REAL,
    FOREIGN KEY(customer_id)
    REFERENCES customers(customer_id)
)
""")

In [6]:
cursor.execute("""
CREATE TABLE order_items (
    item_id INTEGER PRIMARY KEY,
    order_id INTEGER,
    product_id INTEGER,
    quantity INTEGER,
    unit_price REAL,
    discount_pct REAL,
    FOREIGN KEY(order_id)
    REFERENCES orders(order_id),
    FOREIGN KEY(product_id)
    REFERENCES products(product_id)
)
""")

conn.commit()

# Inserting Sample Data

In [7]:
cursor.executescript("""
INSERT INTO customers VALUES
(101, 'Aarav', 'Sharma', 'aarav.s@email.com', 'Mumbai', 'Maharashtra', '2024-01-15', 1),

(102, 'Priya', 'Patel', 'priya.p@email.com', 'Ahmedabad', 'Gujarat', '2024-02-20', 0),

(103, 'Rohan', 'Gupta', 'rohan.g@email.com', 'Delhi', 'Delhi', '2024-03-10', 1),

(104, 'Sneha', 'Reddy', 'sneha.r@email.com', 'Hyderabad', 'Telangana', '2024-04-05', 0),

(105, 'Vikram', 'Singh', 'vikram.s@email.com', 'Jaipur', 'Rajasthan', '2024-05-12', 1),

(106, 'Ananya', 'Iyer', 'ananya.i@email.com', 'Chennai', 'Tamil Nadu', '2024-06-18', 0),

(107, 'Karan', 'Mehta', 'karan.m@email.com', 'Pune', 'Maharashtra', '2024-07-22', 1),

(108, 'Divya', 'Nair', 'divya.n@email.com', 'Kochi', 'Kerala', '2024-08-30', 0);
""")

conn.commit()

In [8]:
cursor.executescript("""
INSERT INTO products VALUES 
(201, 'Wireless Earbuds',     'Electronics', 'BoAt',          1499.00, 250), 
(202, 'Cotton T-Shirt',       'Clothing',    'Levis',         799.00,  500), 
(203, 'Smart Watch',          'Electronics', 'Noise',         2999.00, 150), 
(204, 'Running Shoes',        'Clothing',    'Nike',          4599.00, 120), 
(205, 'Bluetooth Speaker',    'Electronics', 'JBL',           3499.00, 200), 
(206, 'Bedsheet Set',         'Home',        'Spaces',        1299.00, 300), 
(207, 'Laptop Stand',         'Electronics', 'AmazonBasics',  899.00,  180), 
(208, 'Cushion Covers (Set)', 'Home',        'HomeCenter',    599.00,  400);
""")

In [9]:
cursor.executescript("""
INSERT INTO orders VALUES 
(1001, 101, '2024-08-01', 'Delivered',  4498.00), 
(1002, 102, '2024-08-03', 'Delivered',  799.00), 
(1003, 103, '2024-08-05', 'Shipped',    7498.00), 
(1004, 101, '2024-08-10', 'Delivered',  3499.00), 
(1005, 104, '2024-08-12', 'Cancelled',  2999.00), 
(1006, 105, '2024-08-15', 'Delivered',  5898.00), 
(1007, 106, '2024-08-18', 'Pending',    1299.00), 
(1008, 103, '2024-08-20', 'Delivered',  899.00), 
(1009, 107, '2024-08-25', 'Shipped',    6098.00), 
(1010, 108, '2024-08-28', 'Delivered',  1598.00); 
""")

In [10]:
cursor.executescript("""
INSERT INTO order_items VALUES 
(5001, 1001, 201, 2, 1499.00, 0), 
(5002, 1001, 207, 1, 899.00,  10), 
(5003, 1002, 202, 1, 799.00,  0), 
(5004, 1003, 203, 1, 2999.00, 0), 
(5005, 1003, 204, 1, 4599.00, 5), 
(5006, 1004, 205, 1, 3499.00, 0), 
(5007, 1005, 203, 1, 2999.00, 0), 
(5008, 1006, 201, 1, 1499.00, 10), 
(5009, 1006, 204, 1, 4599.00, 5), 
(5010, 1007, 206, 1, 1299.00, 0), 
(5011, 1008, 207, 1, 899.00,  0), 
(5012, 1009, 205, 1, 3499.00, 0), 
(5013, 1009, 208, 2, 599.00,  15), 
(5014, 1010, 206, 1, 1299.00, 0), 
(5015, 1010, 208, 1, 599.00,  0); 
""")

# Verifying Tables and Data

In [11]:
import pandas as pd

pd.read_sql_query("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0    customers
1     products
2       orders
3  order_items

# Checking Row Counts

In [12]:
pd.read_sql_query("""
SELECT COUNT(*) AS Total_Customers
FROM customers;
""", conn)

   Total_Customers
0                8

In [13]:
pd.read_sql_query("""
SELECT COUNT(*) AS Total_Products
FROM products;
""", conn)

   Total_Products
0               8

In [14]:
pd.read_sql_query("""
SELECT COUNT(*) AS Total_Orders
FROM orders;
""", conn)

   Total_Orders
0            10

In [15]:
pd.read_sql_query("""
SELECT COUNT(*) AS Total_Order_Items
FROM order_items;
""", conn)

   Total_Order_Items
0                 15

# Helper Function For Running SQL Queries

In [16]:
def run_query(query):
    return pd.read_sql_query(query, conn)

# Q1 Display All Customer Details

In [17]:
run_query("""
SELECT *
FROM customers;
""")

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
0,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
1,102,Priya,Patel,priya.p@email.com,Ahmedabad,Gujarat,2024-02-20,0
2,103,Rohan,Gupta,rohan.g@email.com,Delhi,Delhi,2024-03-10,1
3,104,Sneha,Reddy,sneha.r@email.com,Hyderabad,Telangana,2024-04-05,0
4,105,Vikram,Singh,vikram.s@email.com,Jaipur,Rajasthan,2024-05-12,1
5,106,Ananya,Iyer,ananya.i@email.com,Chennai,Tamil Nadu,2024-06-18,0
6,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1
7,108,Divya,Nair,divya.n@email.com,Kochi,Kerala,2024-08-30,0

# Q2 Display Customer Names and Cities

In [18]:
run_query("""
SELECT
first_name,
last_name,
city
FROM customers;
""")

  first_name last_name       city
0      Aarav    Sharma     Mumbai
1      Priya     Patel  Ahmedabad
2      Rohan     Gupta      Delhi
3      Sneha     Reddy  Hyderabad
4     Vikram     Singh     Jaipur
5     Ananya      Iyer    Chennai
6      Karan     Mehta       Pune
7      Divya      Nair      Kochi

# Q3 Display Unique Product Categories

In [19]:
run_query("""
SELECT DISTINCT category
FROM products;
""")

      category
0  Electronics
1     Clothing
2         Home

# Q4 Primary Keys

customers → customer_id

products → product_id

orders → order_id

order_items → item_id

Primary Key uniquely identifies each record.

# Q5 Foreign Keys

orders.customer_id → customers.customer_id

order_items.order_id → orders.order_id

order_items.product_id → products.product_id

Foreign Keys maintain relationships between tables.

# verification cells

In [20]:
pd.read_sql_query("""
SELECT COUNT(*) FROM customers
""", conn)

   COUNT(*)
0         8

In [21]:
pd.read_sql_query("""
SELECT COUNT(*) FROM orders
""", conn)

   COUNT(*)
0        10

# Q6 Display Premium Customers

In [22]:
run_query("""
SELECT *
FROM customers
WHERE is_premium = 1;
""")

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
0,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
1,103,Rohan,Gupta,rohan.g@email.com,Delhi,Delhi,2024-03-10,1
2,105,Vikram,Singh,vikram.s@email.com,Jaipur,Rajasthan,2024-05-12,1
3,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1

# Q7 Products With Price Greater Than 1000

In [23]:
run_query("""
SELECT *
FROM products
WHERE unit_price > 1000;
""")

   product_id       product_name     category   brand  unit_price  stock_qty
0         201   Wireless Earbuds  Electronics    BoAt      1499.0        250
1         203        Smart Watch  Electronics   Noise      2999.0        150
2         204      Running Shoes     Clothing    Nike      4599.0        120
3         205  Bluetooth Speaker  Electronics     JBL      3499.0        200
4         206       Bedsheet Set         Home  Spaces      1299.0        300

# Q8 Orders Placed After August 15 2024

In [24]:
run_query("""
SELECT *
FROM orders
WHERE order_date > '2024-08-15';
""")

   order_id  customer_id  order_date     status  total_amount
0      1007          106  2024-08-18    Pending        1299.0
1      1008          103  2024-08-20  Delivered         899.0
2      1009          107  2024-08-25    Shipped        6098.0
3      1010          108  2024-08-28  Delivered        1598.0

# Q9 Customers From Maharashtra

In [25]:
run_query("""
SELECT *
FROM customers
WHERE state = 'Maharashtra';
""")

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
0,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
1,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1

# Q10 Orders Between 2000 and 6000

In [26]:
run_query("""
SELECT *
FROM orders
WHERE total_amount BETWEEN 2000 AND 6000;
""")

   order_id  customer_id  order_date     status  total_amount
0      1001          101  2024-08-01  Delivered        4498.0
1      1004          101  2024-08-10  Delivered        3499.0
2      1005          104  2024-08-12  Cancelled        2999.0
3      1006          105  2024-08-15  Delivered        5898.0

# Q11 Difference Between WHERE and HAVING

WHERE filters rows before aggregation.

HAVING filters groups after aggregation.

Example:

WHERE Sales > 1000

HAVING SUM(Sales) > 5000

# Q12 Difference Between COUNT(*) and COUNT(column)

COUNT(*) counts all rows.

COUNT(column) counts only non-null values in that column.

# Q13 Total Sales Amount

In [27]:
run_query("""
SELECT
SUM(total_amount) AS Total_Sales
FROM orders;
""")

   Total_Sales
0      35085.0

# Q14 Average Product Price

In [28]:
run_query("""
SELECT
AVG(unit_price) AS Average_Price
FROM products;
""")

   Average_Price
0         2024.0

# Q15 Total Orders Per Customer

In [29]:
run_query("""
SELECT
customer_id,
COUNT(order_id) AS Total_Orders
FROM orders
GROUP BY customer_id;
""")

   customer_id  Total_Orders
0          101             2
1          102             1
2          103             2
3          104             1
4          105             1
5          106             1
6          107             1
7          108             1

# Q16 Total Revenue By Product Category

In [30]:
run_query("""
SELECT
category,
SUM(unit_price) AS Revenue
FROM products
GROUP BY category;
""")

      category  Revenue
0     Clothing   5398.0
1  Electronics   8896.0
2         Home   1898.0

# Q17 Maximum Product Price In Each Category

In [31]:
run_query("""
SELECT
category,
MAX(unit_price) AS Max_Price
FROM products
GROUP BY category;
""")

      category  Max_Price
0     Clothing     4599.0
1  Electronics     3499.0
2         Home     1299.0

# Q18 Total Quantity Sold Per Product

In [32]:
run_query("""
SELECT
product_id,
SUM(quantity) AS Total_Quantity
FROM order_items
GROUP BY product_id;
""")

   product_id  Total_Quantity
0         201               3
1         202               1
2         203               2
3         204               2
4         205               2
5         206               2
6         207               2
7         208               3

# Q19 Top 5 Most Expensive Products

In [33]:
run_query("""
SELECT *
FROM products
ORDER BY unit_price DESC
LIMIT 5;
""")

   product_id       product_name     category   brand  unit_price  stock_qty
0         204      Running Shoes     Clothing    Nike      4599.0        120
1         205  Bluetooth Speaker  Electronics     JBL      3499.0        200
2         203        Smart Watch  Electronics   Noise      2999.0        150
3         201   Wireless Earbuds  Electronics    BoAt      1499.0        250
4         206       Bedsheet Set         Home  Spaces      1299.0        300

# Q20 Latest 3 Orders

In [34]:
run_query("""
SELECT *
FROM orders
ORDER BY order_date DESC
LIMIT 3;
""")

   order_id  customer_id  order_date     status  total_amount
0      1010          108  2024-08-28  Delivered        1598.0
1      1009          107  2024-08-25    Shipped        6098.0
2      1008          103  2024-08-20  Delivered         899.0

# Q21 Customer Wise Total Spending

In [35]:
run_query("""
SELECT
c.customer_id,
c.first_name,
c.last_name,
SUM(o.total_amount) AS Total_Spending
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id
ORDER BY Total_Spending DESC;
""")

   customer_id first_name last_name  Total_Spending
0          103      Rohan     Gupta          8397.0
1          101      Aarav    Sharma          7997.0
2          107      Karan     Mehta          6098.0
3          105     Vikram     Singh          5898.0
4          104      Sneha     Reddy          2999.0
5          108      Divya      Nair          1598.0
6          106     Ananya      Iyer          1299.0
7          102      Priya     Patel           799.0

# Q22 Difference Between INNER JOIN and LEFT JOIN

INNER JOIN returns only matching records from both tables.

LEFT JOIN returns all records from the left table and matching records from the right table.

If no match exists, NULL values are returned from the right table.

# Q23 Monthly Sales Trend

In [36]:
run_query("""
SELECT
strftime('%Y-%m', order_date) AS Month,
SUM(total_amount) AS Total_Sales
FROM orders
GROUP BY Month
ORDER BY Month;
""")

     Month  Total_Sales
0  2024-08      35085.0

# Q24 Orders By Status

In [37]:
run_query("""
SELECT
status,
COUNT(*) AS Total_Orders
FROM orders
GROUP BY status;
""")

      status  Total_Orders
0  Cancelled             1
1  Delivered             6
2    Pending             1
3    Shipped             2

# Q25 Premium Customer Orders

In [38]:
run_query("""
SELECT
c.first_name,
c.last_name,
o.order_id,
o.total_amount
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
WHERE c.is_premium = 1;
""")

  first_name last_name  order_id  total_amount
0      Aarav    Sharma      1001        4498.0
1      Rohan     Gupta      1003        7498.0
2      Aarav    Sharma      1004        3499.0
3     Vikram     Singh      1006        5898.0
4      Rohan     Gupta      1008         899.0
5      Karan     Mehta      1009        6098.0

# Q26 Find Duplicate Emails

In [39]:
run_query("""
SELECT
email,
COUNT(*) AS Count_Email
FROM customers
GROUP BY email
HAVING COUNT(*) > 1;
""")

Empty DataFrame
Columns: [email, Count_Email]
Index: []

# Q27 Data Validation Checks

In [40]:
run_query("""
SELECT COUNT(*) AS Total_Customers
FROM customers;
""")

   Total_Customers
0                8

In [41]:
run_query("""
SELECT COUNT(*) AS Total_Products
FROM products;
""")

   Total_Products
0               8

In [42]:
run_query("""
SELECT COUNT(*) AS Total_Orders
FROM orders;
""")

   Total_Orders
0            10

In [43]:
run_query("""
SELECT COUNT(*) AS Total_Order_Items
FROM order_items;
""")

   Total_Order_Items
0                 15

# Business Insights

1. Premium customers contribute significantly to overall sales.
2. Product categories show different revenue contributions.
3. Monthly sales trends help identify business performance.
4. Order status analysis helps track operational efficiency.
5. No duplicate customer emails were found, indicating good data quality.