# Week 1 Assignment
## Basic Data Exploration and Cleaning using Pandas

**Objective:**
Perform data loading, exploration, cleaning, preprocessing, and feature engineering on the provided shopping dataset using Python and Pandas.

# Firstly I Imported the Required Libraries

In [22]:

import pandas as pd
import os

# Then I Load All CSV Files

In [23]:
folder_path = "data/raw"
csv_files = [file for file in os.listdir(folder_path) if file.endswith(".csv")]
print("Total CSV files found:", len(csv_files))
print(csv_files)

Total CSV files found: 98
['backpacks.csv', 'bath-robe.csv', 'bath-towels.csv', 'bathroom-accessories.csv', 'bedsheets.csv', 'belts.csv', 'bodysuit.csv', 'boots.csv', 'boxers.csv', 'bra.csv', 'bracelet.csv', 'briefs.csv', 'camisoles.csv', 'candle-holders.csv', 'caps.csv', 'casual-shoes.csv', 'chair-cover.csv', 'clothing-set.csv', 'clutches.csv', 'co-ords.csv', 'Combined_dataset.csv', 'curtains-and-sheers.csv', 'cutlery.csv', 'dinnerware.csv', 'dresses.csv', 'duffel-bag.csv', 'dungarees.csv', 'dupatta.csv', 'earrings.csv', 'ethnic-dresses.csv', 'face-moisturisers.csv', 'face-wash-and-cleanser.csv', 'flats.csv', 'flip-flops.csv', 'floor-mats--dhurries.csv', 'formal-shoes.csv', 'foundation.csv', 'gloves.csv', 'hair-accessory.csv', 'hair-brush-and-comb.csv', 'hair-cream-and-mask.csv', 'hair-masks.csv', 'handbags.csv', 'headphones.csv', 'heels.csv', 'home-fragrance-set.csv', 'innerwear-vests.csv', 'jackets.csv', 'jeans.csv', 'jumpsuit.csv', 'kurta-sets.csv', 'kurtas.csv', 'kurtis.csv', 'lipstick.csv', 'lounge-pants.csv', 'lounge-shorts.csv', 'lounge-tshirts.csv', 'mangalsutra.csv', 'mobile-accessories.csv', 'night-suits.csv', 'nightdress.csv', 'outdoor-masks.csv', 'palazzos.csv', 'perfume-and-body-mist.csv', 'pillow-covers.csv', 'ring.csv', 'runners.csv', 'sandals.csv', 'saree-blouse.csv', 'sarees.csv', 'scarves.csv', 'shampoo-and-conditioner.csv', 'shaving-essentials.csv', 'sherwani.csv', 'shirts.csv', 'shorts.csv', 'showpieces.csv', 'skirts.csv', 'sports-shoes.csv', 'sunglasses.csv', 'sweaters.csv', 'sweatshirts.csv', 'swim-tops.csv', 'table-covers.csv', 'thermal-bottoms.csv', 'tights.csv', 'tops.csv', 'towel-set.csv', 'track-pants.csv', 'trolley-bag.csv', 'trousers.csv', 'trunk.csv', 'tshirts.csv', 'tunics.csv', 'wall-art.csv', 'wallets.csv', 'watches.csv', 'yoga-mats.csv']

# Then I Combine All CSV Files into One DataFrame

In [24]:

dataframes = []

for file in csv_files:
    file_path = os.path.join(folder_path, file)
    df = pd.read_csv(file_path)
    dataframes.append(df)

combined_df = pd.concat(dataframes, ignore_index=True)

print("All CSV files combined successfully!")

All CSV files combined successfully!

In [25]:
print(f"\nSuccessfully loaded {len(csv_files)} CSV files.")

Successfully loaded 98 CSV files.

# Displaying First Five Records

In [26]:
combined_df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995.0,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899.0,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999.0,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675.0,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899.0,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

# Displaying Last Five Records

In [27]:
combined_df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
1995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890.0,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
1996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900.0,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
1997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950.0,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
1998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295.0,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
1999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699.0,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

# Checking Dataset Shape

In [28]:
print("Shape of Dataset:", combined_df.shape)

Shape of Dataset: (2000, 24)

# Then I Display Column Names

In [29]:
print("Columns:")
print(combined_df.columns.tolist())

Columns:
['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']

# Checking Data Types

In [30]:
print("Data Types:")
print(combined_df.dtypes)

Data Types:
product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said        object
seller_name                object
sizes                         str
videos                     object
seller_information         object
variations                 object
best_offer                    str
more_offers                   str
category                      str
dtype: object

# Then I Check Dataset Information

In [31]:
combined_df.describe()

         product_id       rating  ratings_count  initial_price     discount
count  2.000000e+03  2000.000000    2000.000000    2000.000000  1758.000000
mean   1.713437e+07     3.621500      76.691000    2723.241000    53.503982
std    3.812812e+06     1.374057     241.053946    2408.094809    18.024070
min    5.868460e+05     0.000000       0.000000     249.000000     1.000000
25%    1.511501e+07     3.700000       7.000000    1399.000000    44.000000
50%    1.820890e+07     4.100000      17.000000    1999.000000    56.000000
75%    1.902737e+07     4.300000      58.000000    3299.000000    66.000000
max    2.274707e+07     5.000000    4441.000000   22199.000000    88.000000

# I see the Statistical Summary

In [32]:
combined_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              2000 non-null   int64
 1   title                   2000 non-null   str
 2   product_description     2000 non-null   str
 3   rating                  2000 non-null   float64
 4   ratings_count           2000 non-null   int64
 5   initial_price           2000 non-null   float64
 6   discount                1758 non-null   float64
 7   final_price             2000 non-null   str
 8   currency                2000 non-null   str
 9   images                  2000 non-null   str
 10  delivery_options        2000 non-null   str
 11  product_details         2000 non-null   str
 12  breadcrumbs             2000 non-null   str
 13  product_specifications  2000 non-null   str
 14  amount_of_stars         2000 non-null   str
 15  what_customers_said     854 non-null    object
 16  seller_name             1398 non-null   object
 17  sizes                   2000 non-null   str
 18  videos                  438 non-null    object
 19  seller_information      1398 non-null   object
 20  variations              876 non-null    object
 21  best_offer              2000 non-null   str
 22  more_offers             2000 non-null   str
 23  category                2000 non-null   str
dtypes: float64(3), int64(2), object(5), str(14)
memory usage: 375.1+ KB

In [33]:
print("Number of Rows :", combined_df.shape[0])
print("Number of Columns :", combined_df.shape[1])
print("Total Missing Values :", combined_df.isnull().sum().sum())

Number of Rows : 2000
Number of Columns : 24
Total Missing Values : 5278

# Checking Missing Values

In [34]:
print("Missing Values in Each Column:")
combined_df.isnull().sum()

Missing Values in Each Column:

product_id                   0
title                        0
product_description          0
rating                       0
ratings_count                0
initial_price                0
discount                   242
final_price                  0
currency                     0
images                       0
delivery_options             0
product_details              0
breadcrumbs                  0
product_specifications       0
amount_of_stars              0
what_customers_said       1146
seller_name                602
sizes                        0
videos                    1562
seller_information         602
variations                1124
best_offer                   0
more_offers                  0
category                     0
dtype: int64

# Then I Fill The Missing Values

In [35]:
for column in combined_df.columns:
    if combined_df[column].dtype == "object":
        combined_df[column] = combined_df[column].fillna("Unknown")
    else:
        combined_df[column] = combined_df[column].fillna(0)

print("Missing values handled successfully!")

Missing values handled successfully!

# Removing Duplicate Records

In [36]:
before = combined_df.shape[0]

combined_df = combined_df.drop_duplicates()

after = combined_df.shape[0]

print("Duplicates removed:", before - after)

Duplicates removed: 1000

# Selecting Required Columns

In [37]:
selected_columns = combined_df[
    ["product_id", "title", "final_price", "rating", "category"]
]

selected_columns.head()

   product_id           title  final_price  rating   category
0     8376765     Lino Perros  "₹3,995.00"     3.8  backpacks
1     9136281  Tommy Hilfiger  "₹2,899.00"     4.5  backpacks
2    17633752           Lavie  "₹2,999.00"     4.4  backpacks
3     1376949          F Gear  "₹1,675.00"     4.4  backpacks
4    13939916       MYTRIDENT  "₹2,899.00"     4.7  bath-robe

# Filtering Products with Rating 4 or Above

In [38]:
filtered_products = combined_df[combined_df["rating"] >= 4]

filtered_products.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899.0,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",Unknown,Unknown,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Unknown,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999.0,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",Unknown,Unknown,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Unknown,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675.0,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",Unknown,Unknown,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Unknown,Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899.0,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown,Unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Unknown,Unknown,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,19851824,AVI Living,Grey Solid 500 GSM Pure Cotton Bath Towel,4.0,5,1399.0,65.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",Unknown,Unknown,"[{""size"":""Onesize""}]",Unknown,Unknown,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bath-towels

# Creating New Columns

In [39]:
combined_df["quantity"] = 1

combined_df["total_amount"] = (
    combined_df["final_price"] * combined_df["quantity"]
)

combined_df[
    ["final_price", "quantity", "total_amount"]
].head()

   final_price  quantity total_amount
0  "₹3,995.00"         1  "₹3,995.00"
1  "₹2,899.00"         1  "₹2,899.00"
2  "₹2,999.00"         1  "₹2,999.00"
3  "₹1,675.00"         1  "₹1,675.00"
4  "₹2,899.00"         1  "₹2,899.00"

# Saving the Cleaned Dataset

In [40]:
output_path = "data/cleaned/cleaned_shopping_dataset.csv"

combined_df.to_csv(output_path, index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

# Summary

- Imported required libraries.
- Loaded and combined all CSV files.
- Explored the dataset using head(), tail(), shape, columns and data types.
- Checked and handled missing values.
- Removed duplicate records.
- Selected important columns and filtered rows.
- Created new columns `quantity` and `total_amount`.
- Saved the cleaned dataset as a new CSV file.